# Python, NumPy and Vectorization

In [1]:
import numpy as np
import time

NumPy is a library that extends the base capabilities of python to add a richer data set including more numeric types, vectors, matrices, and many matrix functions. NumPy and python  work together fairly seamlessly. Python arithmetic operators work on NumPy data types and many NumPy functions will accept python data types.

# 1. Vectors

Vectors are ordered arrays of numbers. In notation, vectors are denoted with lower case bold letters such as $\mathbf{x}$.  The elements of a vector are all the **same type**. A vector does not, for example, contain both characters and numbers. The number of elements in the array is often referred to as the *dimension* though mathematicians may prefer *rank*. The vector shown has a dimension of $n$. The elements of a vector can be referenced with an index. In math settings, indexes typically run from 1 to n. In computer science, indexing will typically run from 0 to n-1.  In notation, elements of a vector, when referenced individually will indicate the index in a subscript, for example, the $0^{th}$ element, of the vector $\mathbf{x}$ is $x_0$. Note, the x is not bold in this case.  

NumPy's basic data structure is an indexable, n-dimensional *array* containing elements of the same type (`dtype`). Right away, you may notice we have overloaded the term 'dimension'. Above, it was the number of elements in the vector, here, dimension refers to the number of indexes of an array. A one-dimensional or 1-D array has one index.
 - 1-D array, shape (n,): n elements indexed [0] through [n-1]

Data creation routines in NumPy will generally have a first parameter which is the shape of the object. This can either be a single value for a 1-D result or a tuple (n,m,...) specifying the shape of the result. Below are examples of creating vectors using these routines.

In [2]:
#Numpy routines which allocate memory and fill arrays with value
a=np.zeros(4)
print(f"np.zeros(4): a={a}, a shape={a.shape}, a data type={a.dtype}")
a=np.zeros((4,))
print(f"np.zeros((4,)): a={a}, a shape={a.shape}, a data type={a.dtype}")
a=np.random.random_sample(4)
print(f"np.random.random_sample(4): a={a}, a shape={a.shape}, a data type={a.dtype}")

np.zeros(4): a=[0. 0. 0. 0.], a shape=(4,), a data type=float64
np.zeros((4,)): a=[0. 0. 0. 0.], a shape=(4,), a data type=float64
np.random.random_sample(4): a=[0.13532984 0.27191608 0.73986321 0.06795245], a shape=(4,), a data type=float64


Some data creation routines do not take a shape tuple:

In [3]:
#Numpy routines which allocate memory and fill arrays with value but do not accept shape as input argument
a=np.arange(4.)
print(f"np.arange(4.): a={a}, a shape={a.shape}, a data type={a.dtype}")
a=np.random.rand(4)
print(f"np.random.rand(4): a={a}, a shape={a.shape}, a data type={a.dtype}")

np.arange(4.): a=[0. 1. 2. 3.], a shape=(4,), a data type=float64
np.random.rand(4): a=[0.85042586 0.79483134 0.8702145  0.91408718], a shape=(4,), a data type=float64


Values can be specified manually as well:

In [4]:
#Numpy routines which allocate memory and fill with user specified values
a=np.array([5,4,3,2])
print(f"np.array([5,4,3,2]): a={a}, a shape={a.shape}, a data type={a.dtype}")
a=np.array([5.,4,3,2])
print(f"np.array([5.,4,3,2]): a={a}, a shape={a.shape}, a data type={a.dtype}")

np.array([5,4,3,2]): a=[5 4 3 2], a shape=(4,), a data type=int32
np.array([5.,4,3,2]): a=[5. 4. 3. 2.], a shape=(4,), a data type=float64


These have all created a one-dimensional vector  `a` with four elements. `a.shape` returns the dimensions. Here we see a.shape = `(4,)` indicating a 1-d array with 4 elements.  

# 2.Operations on Vectors
## 2.1. Indexing
Elements of vectors can be accessed via indexing and slicing. NumPy provides a very complete set of indexing and slicing capabilities. Reference [Slicing and Indexing](https://NumPy.org/doc/stable/reference/arrays.indexing.html) for more details.  
- **Indexing** means referring to *an element* of an array by its position within the array.  
- **Slicing** means getting a *subset* of elements from an array based on their indices.  

NumPy starts indexing at zero so the 3rd element of an vector $\mathbf{a}$ is `a[2]`.

In [6]:
#vector indexing operations on 1-D vectors
a=np.arange(10)
print(a)

#access an element
print(f"a[2].shape:{a[2].shape} a[2]:{a[2]}, Accessing an element returns a scalar")

#access the last elementi megativr indexes count from the end
print(f"a[-1]:{a[-1]}")

#indexs must be within the range of the vector or they will produce an error
try: 
    c=a[10]
except Exception as e:
    print("The error is:", e)

[0 1 2 3 4 5 6 7 8 9]
a[2].shape:() a[2]:2, Accessing an element returns a scalar
a[-1]:9
The error is: index 10 is out of bounds for axis 0 with size 10


## 2.2. Slicing
Slicing creates an array of indices using a set of three values (`start:stop:step`). A subset of values is also valid. Its use is best explained by example:

In [7]:
#vector slicing operations
a=np.arange(10)
print(f"a={a}")

#access 5 consecutive elements (start:stop:step)
c=a[2:7:1]
print(f"a[2:7:1]={c}")

#access 3 elements separated by two
c=a[2:7:2]
print(f"a[2:7:2]={c}")

#access all elements index 3 and above
c=a[3:]
print(f"a[3:]={c}")

#access all elements below index 3
c=a[:3]
print(f"a[:3]={c}")

#access all elements
c=a[:]
print(f"a[:]={c}")

a=[0 1 2 3 4 5 6 7 8 9]
a[2:7:1]=[2 3 4 5 6]
a[2:7:2]=[2 4 6]
a[3:]=[3 4 5 6 7 8 9]
a[:3]=[0 1 2]
a[:]=[0 1 2 3 4 5 6 7 8 9]


## 2.3. Single Vector Operations

In [10]:
a=np.array([1,2,3,4])
print(f"a: {a}")

#negate elements of a
b=-a
print(f"(b=-a): {b}")

#sum all elements of ai returns a scalar
b=np.sum(a)
print(f"b=np.sum(a): {b}")

b=np.mean(a)
print(f"b=np.mean(a): {b}")

b=a**2
print(f"b=a**2: {b}")

a: [1 2 3 4]
(b=-a): [-1 -2 -3 -4]
b=np.sum(a): 10
b=np.mean(a): 2.5
b=a**2: [ 1  4  9 16]


## 2.4. Vector - Vector Element Wise Operations
Most of the NumPy arithmetic, logical and comparison operations apply to vectors as well. These operators work on an element-by-element basis. For example 
$$ c_i = a_i + b_i $$

In [20]:
a=np.array([1,2,3,4])
b=np.array([-1,-2, 3,4])
print(f"Binary operators work element wise: {a+b}")
print(f"Binary operators work element wise: {a*b}")
print(f"Binary operators work element wise: {a-b}")

Binary operators work element wise: [0 0 6 8]
Binary operators work element wise: [-1 -4  9 16]
Binary operators work element wise: [2 4 0 0]


The vectors must be of the **same size**:

In [19]:
c=np.array([1,2])

try:
    d=a*c
except Exception as e:
    print("The error is:", e)

The error is: operands could not be broadcast together with shapes (4,) (2,) 


## 2.5. Scalar Vector Operations
Vectors can be 'scaled' by scalar values. A scalar value is just a number. The scalar multiplies all the elements of the vector.

In [23]:
a=np.array([1,2,3,4])

#multiply by a scalar
b=5*a
print(f"(b=5*a): {b}")

(b=5*a): [ 5 10 15 20]


## 2.6. Vector - Vector Dot Product
The dot product is a mainstay of Linear Algebra and NumPy. The dot product multiplies the values in two vectors element-wise and then sums the result. Vector dot product requires **the dimensions of the two vectors to be the same**. 

Let's implement our own version of the dot product below:

**Using a for loop**, implement a function which returns the dot product of two vectors. The function to return given inputs $a$ and $b$:
$$ x = \sum_{i=0}^{n-1} a_i b_i $$
Assume both `a` and `b` are the same shape.

In [25]:
def dot_product(a,b):
    x=0
    for i in range(a.shape[0]):
        x=x+a[i]*b[i]
    return x

In [27]:
#testing with 1-D array
a=np.array([1,2,3,4])
b=np.array([-1,4,3,2])
print(f"dot_product(a,b): {dot_product(a,b)}")

dot_product(a,b): 24


Note, the dot product is expected to return a scalar value. 

Let's try the same operations using `np.dot`.  

In [29]:
#testing with 1-D array
a=np.array([1,2,3,4])
b=np.array([-1,4,3,2])
c=np.dot(a,b)
print(f"NumPy 1-D np.dot(a, b) = {c}, np.dot(a, b).shape = {c.shape} ") 
c = np.dot(b, a)
print(f"NumPy 1-D np.dot(b, a) = {c}, np.dot(a, b).shape = {c.shape} ")

NumPy 1-D np.dot(a, b) = 24, np.dot(a, b).shape = () 
NumPy 1-D np.dot(b, a) = 24, np.dot(a, b).shape = () 


Above, you will note that the results for 1-D matched our implementation.

## 2.7. The Need for Speed: Vector vs For Loop
We utilized the NumPy  library because it improves speed memory efficiency. Let's demonstrate:

In [32]:
np.random.seed(1)
a=np.random.rand(10000000)
b=np.random.rand(10000000)

start=time.time() #capture start time
c=np.dot(a,b)
end=time.time() #capture end time

print(f"np.dot(a,b)={c:.4f}")
print(f"Vectorized version duration: {1000*(end-start):.4f} ms")

start=time.time() #capture start time
c=dot_product(a,b)
end=time.time() #capture end time

print(f"np.dot_product(a,b)={c:.4f}")
print(f"Loop version duration: {1000*(end-start):.4f} ms")

del(a)
del(b)

np.dot(a,b)=2501072.5817
Vectorized version duration: 9.0017 ms
np.dot_product(a,b)=2501072.5817
Loop version duration: 2651.0341 ms


So, vectorization provides a large speed up in this example. This is because NumPy makes better use of available data parallelism in the underlying hardware. GPU's and modern CPU's implement Single Instruction, Multiple Data (SIMD) pipelines allowing multiple operations to be issued in parallel. This is critical in Machine Learning where the data sets are often very large.

# 3. Matrices

Matrices, are two dimensional arrays. The elements of a matrix are all of the same type. In notation, matrices are denoted with capitol, bold letter such as $\mathbf{X}$. In this notebook, `m` is often the number of rows and `n` the number of columns. The elements of a matrix can be referenced with a two dimensional index. In math settings, numbers in the index typically run from 1 to n. In computer science , indexing will run from 0 to n-1. In generic matrix notation, 1st index is row, 2nd is column

NumPy's basic data structure is an indexable, n-dimensional *array* containing elements of the same type (`dtype`). These were described earlier. Matrices have a two-dimensional (2-D) index [m,n]. Below you will review: 
- data creation
- slicing and indexing

The same functions that created 1-D vectors will create 2-D or n-D arrays. Here are some examples. Below, the shape tuple is provided to achieve a 2-D result. Notice how NumPy uses brackets to denote each dimension. Notice further than NumPy, when printing, will print one row per line.

In [34]:
a=np.zeros((1,5))
print(f"a shape={a.shape}, a={a}")

a=np.zeros((2,2))
print(f"a shape={a.shape}, a={a}")

a=np.random.random_sample((1,1))
print(f"a shape={a.shape}, a={a}")

a shape=(1, 5), a=[[0. 0. 0. 0. 0.]]
a shape=(2, 2), a=[[0. 0.]
 [0. 0.]]
a shape=(1, 1), a=[[0.04997798]]


One can also manually specify data. Dimensions are specified with additional brackets matching the format in the printing above.

In [35]:
# NumPy routines which allocate memory and fill with user specified values
a = np.array([[5], [4], [3]])
print(f" a shape = {a.shape}, np.array: a = {a}")
a = np.array([[5],   # One can also
              [4],   # separate values
              [3]]) #into separate rows
print(f" a shape = {a.shape}, np.array: a = {a}")

 a shape = (3, 1), np.array: a = [[5]
 [4]
 [3]]
 a shape = (3, 1), np.array: a = [[5]
 [4]
 [3]]


# 4.Operations on Vectors
## 4.1. Indexing
Matrices include a second index. The two indexes describe [row, column]. Access can either return an element or a row/column. See below:

In [36]:
#vector indexing operations on matrices
a = np.arange(6).reshape(-1, 2)   #reshape is a convenient way to create matrices
print(f"a.shape: {a.shape}, \na= {a}")

#access an element
print(f"\na[2,0].shape:   {a[2, 0].shape}, a[2,0] = {a[2, 0]},     type(a[2,0]) = {type(a[2, 0])} Accessing an element returns a scalar\n")

#access a row
print(f"a[2].shape:   {a[2].shape}, a[2]   = {a[2]}, type(a[2])   = {type(a[2])}")

a.shape: (3, 2), 
a= [[0 1]
 [2 3]
 [4 5]]

a[2,0].shape:   (), a[2,0] = 4,     type(a[2,0]) = <class 'numpy.int32'> Accessing an element returns a scalar

a[2].shape:   (2,), a[2]   = [4 5], type(a[2])   = <class 'numpy.ndarray'>


Accessing a matrix by just specifying the row will return a *1-D vector*.

**Reshape**  
The previous example used [reshape](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html) to shape the array.  
`a = np.arange(6).reshape(-1, 2) `   
This line of code first created a *1-D Vector* of six elements. It then reshaped that vector into a *2-D* array using the reshape command. This could have been written:  
`a = np.arange(6).reshape(3, 2) `  
To arrive at the same 3 row, 2 column array.
The -1 argument tells the routine to compute the number of rows given the size of the array and the number of columns.


## 4.2 Slicing
Slicing creates an array of indices using a set of three values (`start:stop:step`). A subset of values is also valid. Its use is best explained by example:

In [38]:
#vector 2-D slicing operations
a = np.arange(20).reshape(-1, 10)
print(f"a = \n{a}")

#access 5 consecutive elements (start:stop:step)
print("a[0, 2:7:1] = ", a[0, 2:7:1], ",  a[0, 2:7:1].shape =", a[0, 2:7:1].shape, "a 1-D array")

#access 5 consecutive elements (start:stop:step) in two rows
print("a[:, 2:7:1] = \n", a[:, 2:7:1], ",  a[:, 2:7:1].shape =", a[:, 2:7:1].shape, "a 2-D array")

# access all elements
print("a[:,:] = \n", a[:,:], ",  a[:,:].shape =", a[:,:].shape)

# access all elements in one row (very common usage)
print("a[1,:] = ", a[1,:], ",  a[1,:].shape =", a[1,:].shape, "a 1-D array")
print("a[1]   = ", a[1],   ",  a[1].shape   =", a[1].shape, "a 1-D array")


a = 
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
a[0, 2:7:1] =  [2 3 4 5 6] ,  a[0, 2:7:1].shape = (5,) a 1-D array
a[:, 2:7:1] = 
 [[ 2  3  4  5  6]
 [12 13 14 15 16]] ,  a[:, 2:7:1].shape = (2, 5) a 2-D array
a[:,:] = 
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]] ,  a[:,:].shape = (2, 10)
a[1,:] =  [10 11 12 13 14 15 16 17 18 19] ,  a[1,:].shape = (10,) a 1-D array
a[1]   =  [10 11 12 13 14 15 16 17 18 19] ,  a[1].shape   = (10,) a 1-D array
